# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDbconnect():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dbconnect(self):
    self.driver.get("/login?next=%2F")
    self.driver.set_window_size(1280, 720)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("admin@dev2.koleso.ru")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("adminpass")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".directory-toggle").click()
    self.driver.find_element(By.LINK_TEXT, "Add New Server").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("subscribe")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    self.driver.find_element(By.NAME, "host").click()
    self.driver.find_element(By.NAME, "host").send_keys("subscribe-cp-postgres")
    self.driver.find_element(By.NAME, "db").click()
    self.driver.find_element(By.NAME, "db").send_keys("subscribe-cp")
    self.driver.find_element(By.NAME, "username").send_keys("subscribe-user")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("subscribe-password")
    self.driver.find_element(By.NAME, "save_password").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"Save\"]").click()
    self.driver.close()
  
